### ISSUE TITLE
Not compatible with silverstripe/assets requirements

### ISSUE THREAD

**Issue by dawb** [fullscreeninteractive/silverstripe-azure-blob-storage#3]
Hi,

We are running into issues with league/flysystem-azure-blob-storage not being compatible with the requirements of silverstripe/assets 1.11.0

league/flysystem-azure-blob-storage requires league/flysystem ^3.0.0 or higher but silverstripe/assets is only compatiable with ^1.0.70

Has anyone managed to install this with recent versions of the Silverstripe recipe? I've reached out to the managers of silverstripe/assets and they advised a move to flystem in version 5 of the CMS but that doesn't help with current websites.

Thanks
Will

![Screen Shot 2022-10-04 at 10 15 45 AM](https://user-images.githubusercontent.com/777930/193684056-4f25d2e7-23b7-4f4f-8742-74d109908fe2.png)

**Comment by dawb** [comment]
To resolve this we have reverted back to the previous 1.2 release but have had to use the following requirement in the project composer file to resolve the previous conflicts.

```
"guzzlehttp/psr7": "2.4.1 as 1.5.0",
"fullscreeninteractive/silverstripe-azure-blob-storage": "1.2.0"
```

Would it be possible to also advise how the AZURE_CONNECTION_URL property should look?
We have tried `AZURE_CONNECTION_URL=company.blob.core.windows.net` but this returns the following error.

![Screen Shot 2022-10-04 at 12 41 37 PM](https://user-images.githubusercontent.com/777930/193704896-b886eda2-2c68-41f8-a3ce-c40640fc5741.png)

**Comment by wilr** [comment]
@dawb Connect URL for us looks something like: `DefaultEndpointsProtocol=https;AccountName=ABC;AccountKey=CDD;EndpointSuffix=core.windows.net`. Yes the latest dev-main line tracks the development of latest Silverstripe framework dev-main at this stage.

**Comment by dawb** [comment]
great, thanks @wilr. We'll look to use dev-main branch instead, thanks for the help

We have dropped back to 1.2.0 and have downgraded to Silverstripe 4.10 which resolves the requirements for graphql issues as well.
